name: "@cap/recording"
author: "Cap Software"
changelog: "CHANGELOG.md"
targets:
  - host: macos-latest
    target: x86_64-apple-darwin
    build: |
      brew install ffmpeg
      pnpm build
  - host: macos-latest  
    target: aarch64-apple-darwin
    build: |
      brew install ffmpeg
      pnpm build
  - host: windows-latest
    target: x86_64-pc-windows-msvc
    build: |
      # Install FFmpeg dependencies
      pnpm build
  - host: ubuntu-latest
    target: x86_64-unknown-linux-gnu
    build: |
      sudo apt-get update
      sudo apt-get install -y libavcodec-dev libavformat-dev libavutil-dev
      pnpm build
  - host: ubuntu-latest
    target: aarch64-unknown-linux-gnu
    build: |
      sudo apt-get update
      sudo apt-get install -y libavcodec-dev libavformat-dev libavutil-dev gcc-aarch64-linux-gnu
      pnpm build
