/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface RecordingConfig {
  outputPath: string
  screenId?: number
  windowId?: number
  captureSystemAudio?: boolean
  fps?: number
}
export declare function listAvailableScreens(): Array<ScreenInfo>
export declare function listAvailableWindows(): Array<WindowInfo>
export interface ScreenInfo {
  id: number
  name: string
  refreshRate: number
}
export interface WindowInfo {
  id: number
  title: string
  ownerName: string
}
export declare function hasScreenCapturePermission(): boolean
export declare class CapRecorder {
  constructor()
  startRecording(config: RecordingConfig): Promise<void>
  stopRecording(): Promise<string>
  pauseRecording(): Promise<void>
  resumeRecording(): Promise<void>
  cancelRecording(): Promise<void>
}
