[build]
# Enable static linking for FFmpeg on Windows
[target.x86_64-pc-windows-msvc]
rustflags = [
    "-C", "target-feature=+crt-static",
    "-L", "native=C:/vcpkg/installed/x64-windows-static/lib",
]

[target.x86_64-pc-windows-msvc.env]
PKG_CONFIG_PATH = "C:/vcpkg/installed/x64-windows-static/lib/pkgconfig"
FFMPEG_DIR = "C:/vcpkg/installed/x64-windows-static"
VCPKG_ROOT = "C:/vcpkg"

# macOS specific configurations
[target.x86_64-apple-darwin]
rustflags = [
    "-C", "link-arg=-undefined",
    "-C", "link-arg=dynamic_lookup",
]

[target.aarch64-apple-darwin]
rustflags = [
    "-C", "link-arg=-undefined", 
    "-C", "link-arg=dynamic_lookup",
]

# Linux configurations with enhanced V4L2 support
[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C", "link-arg=-Wl,--as-needed",
]

[target.x86_64-unknown-linux-gnu.env]
# Enhanced bindgen configuration for V4L2 compatibility
BINDGEN_EXTRA_CLANG_ARGS = "-I/usr/include/linux -I/usr/include --verbose"
V4L2_SYS_INCLUDE_PATH = "/usr/include"
LIBCLANG_PATH = "/usr/lib/llvm-14/lib"
# Help bindgen work around problematic V4L2 structures
DOCS_RS = "1"

[env]
# Common environment variables
PKG_CONFIG_ALLOW_SYSTEM_LIBS = "1"
PKG_CONFIG_ALLOW_SYSTEM_CFLAGS = "1"