[build]
# Enable static linking for FFmpeg on Windows
[target.x86_64-pc-windows-msvc]
rustflags = [
    "-C", "target-feature=+crt-static",
    "-L", "native=${VCPKG_ROOT}/installed/x64-windows-static/lib",
]

[target.x86_64-pc-windows-msvc.env]
PKG_CONFIG_PATH = "${VCPKG_ROOT}/installed/x64-windows-static/lib/pkgconfig"
FFMPEG_DIR = "${VCPKG_ROOT}/installed/x64-windows-static"

# macOS specific configurations
[target.x86_64-apple-darwin]
rustflags = [
    "-C", "link-arg=-undefined",
    "-C", "link-arg=dynamic_lookup",
]

[target.aarch64-apple-darwin]
rustflags = [
    "-C", "link-arg=-undefined", 
    "-C", "link-arg=dynamic_lookup",
]

# Linux configurations
[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C", "link-arg=-Wl,--as-needed",
]

[env]
# Common environment variables
PKG_CONFIG_ALLOW_SYSTEM_LIBS = "1"
PKG_CONFIG_ALLOW_SYSTEM_CFLAGS = "1"
