[build]
# Enable static linking for FFmpeg on Windows
[target.x86_64-pc-windows-msvc]
rustflags = [
    "-C", "target-feature=+crt-static",
    "-L", "native=${VCPKG_ROOT}/installed/x64-windows-static/lib",
    # Add Windows system libraries for FFmpeg Media Foundation and DirectShow support
    "-l", "strmiids",
    "-l", "mfuuid", 
    "-l", "mf",
    "-l", "mfplat",
    "-l", "ole32",
    "-l", "oleaut32",
    "-l", "winmm",
    "-l", "uuid",
    "-l", "quartz",
]

[target.x86_64-pc-windows-msvc.env]
PKG_CONFIG_PATH = "${VCPKG_ROOT}/installed/x64-windows-static/lib/pkgconfig"
FFMPEG_DIR = "${VCPKG_ROOT}/installed/x64-windows-static"

# macOS specific configurations
[target.x86_64-apple-darwin]
rustflags = [
    "-C", "link-arg=-undefined",
    "-C", "link-arg=dynamic_lookup",
]

[target.x86_64-apple-darwin.env]
FFMPEG_DIR = "${FFMPEG_DIR}"
PKG_CONFIG_PATH = "${PKG_CONFIG_PATH}"
C_INCLUDE_PATH = "${C_INCLUDE_PATH}"
LIBRARY_PATH = "${LIBRARY_PATH}"
BINDGEN_EXTRA_CLANG_ARGS = "${BINDGEN_EXTRA_CLANG_ARGS}"
FFMPEG_SYS_NO_DEFAULT_INCLUDE_PATHS = "${FFMPEG_SYS_NO_DEFAULT_INCLUDE_PATHS}"

[target.aarch64-apple-darwin]
rustflags = [
    "-C", "link-arg=-undefined", 
    "-C", "link-arg=dynamic_lookup",
]

[target.aarch64-apple-darwin.env]
FFMPEG_DIR = "${FFMPEG_DIR}"
PKG_CONFIG_PATH = "${PKG_CONFIG_PATH}"
C_INCLUDE_PATH = "${C_INCLUDE_PATH}"
LIBRARY_PATH = "${LIBRARY_PATH}"
BINDGEN_EXTRA_CLANG_ARGS = "${BINDGEN_EXTRA_CLANG_ARGS}"
FFMPEG_SYS_NO_DEFAULT_INCLUDE_PATHS = "${FFMPEG_SYS_NO_DEFAULT_INCLUDE_PATHS}"

# Linux configurations
[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C", "link-arg=-Wl,--as-needed",
]

[env]
# Common environment variables
PKG_CONFIG_ALLOW_SYSTEM_LIBS = "1"
PKG_CONFIG_ALLOW_SYSTEM_CFLAGS = "1"
